apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\wrigh\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\wrigh\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: client
    spec:
      containers:
        - args:
            - npm
            - start
          image: wrightchin/mern-demo-client-34:latest
          name: mern-demo-react-client
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /usr/app
              name: client-claim0
            - mountPath: /usr/app/node_modules
              name: client-claim1
      restartPolicy: Always
      volumes:
        - name: client-claim0
          persistentVolumeClaim:
            claimName: client-claim0
        - name: client-claim1
          persistentVolumeClaim:
            claimName: client-claim1
status: {}
