apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\wrigh\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
